### PR TITLE
Update cassandra.cql

### PR DESCRIPTION
**Pull request by inesromdhani**
fix the script, remove the ";" after declaring the PRIMARY KEY for each TABLE

### CODE REVIEW

**Comment by deruelle** [comment]
Thanks @inesromdhani for the contribution. Can you sign the Contributor License Agreement at http://www.telestax.com/open-source/#Contribute so we can accept the contributions and acknowledge you ?

**Comment by inesromdhani** [comment]
Done !!

**Comment by deruelle** [comment]
thanks @inesromdhani ! @vetss please review !

**Comment by vetss** [comment]
Hello @inesromdhani 

1) I merged your update, thanks for ypur work

2) please remember that you do not need to run this script by yourself because SMSC GW creates all needed tables by it self. This script is only for your info.

**Comment by inesromdhani** [comment]
Thank you @vetss for your care, i am happy to trust my work

**Comment by deruelle** [comment]
Thanks @inesromdhani. Your contribution is acknowledged at https://telestax.com/acknowledgements/

**Comment by inesromdhani** [comment]
Thanks @deruelle

**Pull request merged**
