### PR TITLE
Generate CDRs on message rejection by MProc rule.

### PR DESCRIPTION
**Pull request by mniemiec**
PR for generating CDRs on message rejection by MProc rule.

### CODE REVIEW

**Comment by vetss** [comment]
Hello @mniemiec 

it looks like we faced again with an issue because of which I could not accept another PR for CDR logging. Let's make a design discussing before of making such sort significant updates.

1) You added a new Exception type, may be we can just add CDR logging just into a place where we throw that Exception to avoid of extra capturing. Such extra capturing makes code more complicated.

2) You are going to add CDRs for a submitting parts and this mean we need to have some logically clear set of CDRs that will cover a set of cases not only a case when mproc rules rejects it. We can provide CDRs for both cases (submitting accepted / rejected) but we can cover as for now only rejected messages. We need to sort out causes and may be other needed fields. The cause "failed" is used for another cases and may not be used for this case. I think you remember I wrote a special message with details for this case in your portal (but this info was not unfortunately take into account by you).
We can start again with that point for discussing to agree for a solution that fits both of us. Thanks for understanding.

**Comment by ovoo-unif** [comment]
Hi Sergey,

regarding:

1. You don't need extra exception capturing since: "SmsRejectionException extends SmscProcessingException". Right?

2. When the message is rejected/dropped by mproc rule. It is basically a permanent failure. Customer requires CDRs in such cases. If you don't like this kind of handling, please update or propose another way.

With kind regards,
adam

**Comment by vetss** [comment]
Hello @ovoo-unif 

> You don't need extra exception capturing since: "SmsRejectionException extends
> SmscProcessingException". Right?

I was explaining not how many Exceptions do we need to catch but for the solution to avoid of throwing / catching an Exception for this CDR logging case (it seems me more clear in term of further SMSC code implementation and avoiding of cathing of Exceptions whenever it is possible and reasonable).
So you are right. Your implemenetation of catching of the Exception will work of cause for the task your trying to achieve, my comment was for the way to implement it better.

> When the message is rejected/dropped by mproc rule. It is basically a permanent failure. 
> Customer requires CDRs in such cases. If you don't like this kind of handling, 

Yes it is a permanant failure and I understand the customer's wish to see such issue. The problem is if we want to cover such cases we need to provide a solution only for this concrete case but also for a whole scope of cases (rejections in a submitting phase).

> please update or propose another way.

Please see my comments in https://ovoo.com.pl/redmine/issues/669, I have already provided them. Let me copypaste them here for simplifying a discussion:

```
2) for the extra CDR logging
20161128-Unifonic-Telestax-Partnership_technical (https://docs.google.com/document/d/13f8whPN2IUj5X1pa2odC9hJYmDeTvUuEqGQkwX9HgXA/edit),
chapter 3.9.4:
SMS Sending Request Status

Not clear what does it mean "SMS sending request" ? Does "sending" mean a) customer->SMSC leg or b) SMSC->operator leg ?
For b) case we have already CDRs
For a) case - this is a submit part. I beleive that if a message is accepted for delivering that we do not need of CDRs this step (they will be generated at the leg/step b) ). So the case make sense as "CDR when a message is rejected in the submit part".

In this case (case b):

This functionality must be implemented at TxSmpp SBB levels to cover not only SubmitCommonSbb case but also concrete

CDR reasons:
ocs_rejected
this is present in CdrGenerator file and fully implemented - a case when a message is rejected by a diameter server

mproc_rejected
mproc_dropped
- these two options are already present in CdrGenerator but implemented only in Charging SBB. We need to add it separately in SubmitCommonSbb for other cases. May be we can log here as a reason a new field MProcMessage.addMprocNote(String note). - a case when a message is rejected / dropped by a mproc rule.
A differnce between reject / drop of a message is that in a reject case we return an error code to an originater and in a drop case we return a success response to an originator but then drop a message without delivery attempts.

submit_failed_mo
submit_failed_hr
submit_failed_esme
submit_failed_sip
submit_failed_http
- these are new value - for cases when incoming message rejection is not because of CDR / MPROC cases but because of some SMSC GW administrative restrictions (for example is we reject all SS7 originated messages) / failure / overload.

As for an extra configuring if we will generate such CDRs (all submit options - ocs_rejected, mproc_rejected, mproc_dropped, submit_failed_mo):

CLI option . short name - generateSubmitFailureCdr
Description: Generate CDR for a submit failure case
```

**Comment by mniemiec** [comment]
Hello @vetss 
I added a new PR for generating CDR on message rejection based on reject-cdr-pr-01 branch https://github.com/RestComm/smscgateway/pull/233. It contains corrections based on your comments and our discussion. Please let me know if you agree with this solution.

**Comment by vetss** [comment]
I am closing this PR because of processing of a new one.

**Pull request closed without merging**
