### PR TITLE
Enhancement - WIP Issue#179 - TlvSet modifications

### PR DESCRIPTION
**Pull request by abdulazizali77**
InitialWIP #179 PR, @vetss @nhanth87 if you have the time, could you look at my initial commit and see if im on the correct path, thanks!

TODO:
~MProcMessage.getTlvSet()~
~PostArrivalProcessor.removeTLVParameter(short tag); - remove of TVL parameter from a message~
Update mproc rules
~option: "tlv_11 333" - true if a TLV with tag 11 == 333~
~action: "remove_tlv 11" - remove TLV with tag 11~
update smsc-cli docs

### CODE REVIEW

**Comment by abdulazizali77** [comment]
@vetss By the last item you mentioned
>action: "remove_tlv 11" - remove TLV with tag 11

Should we actually add MProcRule.removeTlv(MProcMessage message, short tag) ?

**Comment by abdulazizali77** [comment]
hi @vetss , please have a look, from our discussions, i have:
1) squashed the commits
2) removed matchesTlv
3) add processing for "tlv_*" and "remove_tlv". 
     -variable naming might not be correct
     -tlvValueToMatch couldve been defined as String but i have made it a byte array as per tlv
     -some logic in the handlers might be incorrect

Please correct me where i am wrong, thank you!

**Comment by vetss** [comment]
Hello @abdulazizali77 
I have added your commit and some mu fixes. Please check my comments in https://github.com/RestComm/smscgateway/issues/179

Thanks for your work.

**Comment by abdulazizali77** [comment]
Thanks again @vetss

**Pull request closed without merging**
